version : 2
jobs :
  build :
    docker:
          - image: bitnami/php-fpm:7.2
        working_directory: ~/circle
        steps:
          - checkout
          - restore_cache:
              key: server-dependencies-cache-{{ checksum "./composer.json" }}
          - run:
              name: Build Server
              command: php composer.phar install --prefer-dist
          - save_cache:
              key: server-dependencies-cache-{{ checksum "./composer.json" }}
              paths:
                - ./server/vendor
          - run:
              name: Test Server
              command: php vendor/bin/phpunit
    #      - run:
    #          name: Test Migration Up
    #          command: cd server && php artisan migrate --database=migration-test
    #      - run:
    #          name: Test Migration Down
    #          command: cd server && php artisan migrate:rollback --database=migration-test
          - run:
              name: Bump build number
              command: touch .env && echo "APP_BUILD_NUMBER=$CIRCLE_BUILD_NUM" >> .env && echo "APP_BUILD_TIMESTAMP=$(date +%s)" >> .env
          - persist_to_workspace:
              root: .
              paths:
                - server

