version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: bitnami/php-fpm:7.2

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/circle

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys: server-dependencies-cache-{{ checksum "composer.json" }}

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: server-dependencies-cache-{{ checksum "composer.json" }}

      # run tests!
      - run: php vendor/bin/phpunit